Rebuild serializer on model refs update
georgebv/drf-pydantic pull request #28
Opened 2024-08-14 06:29 UTC by JargeZ

I just found it a problem for me
Please check ongoing fixes

2024-08-14 06:54 UTC, mahenzon commented on src/drf_pydantic/base_model.py
> +            )
can be replaced with
```suggestion
            cls.drf_serializer = create_serializer_from_model(cls)
```
since we know the attribute's name

2024-08-14 18:35 UTC, georgebv commented
Can you please provide a code snippet showing the problem? I'd like to understand the use case.

2024-08-14 23:49 UTC, JargeZ commented
It is a case at least with recursive models
```python

class Task(DRFBaseModel):
    id: UUID
    subtasks: list["Task"] | None = None
    
Task.update_forward_refs()  # v1 deprecated
Task.model_rebuild()
```

2024-08-15 01:29 UTC, georgebv requested changes

2024-08-15 01:29 UTC, georgebv commented on src/drf_pydantic/base_model.py
> +        _types_namespace: dict[str, Any] | None = None,
Please use python 3.9 compatible type hints.

2024-08-15 01:31 UTC, georgebv commented
@JargeZ thank you. We don't support pydantic v1 so adding that for v2 should be enough. Can you please add some unit tests for recursive models and for rebuilding the model?

2024-08-28 00:13 UTC, georgebv commented
@JargeZ sorry for delayed response. I looked into this and I am confused as to how we should represent recursive models in DRF. There are ways to achieve this with recursive functions, but I don't think that's what we want.

Can you provide an example of what you expect the resulting recursive DRF serializer to look like?

2025-08-10 23:05 UTC, georgebv commented
Closed due to inactivity

2025-08-10 23:05 UTC, closed without merging